# Generated by Django 5.0.4 on 2024-04-17 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=250)),
                ('state', models.CharField(choices=[('Andhra_Pradesh', 'Andhra_Pradesh'), ('Arunachal_Pradesh', 'Arunachal_Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal_Pradesh', 'Himachal_Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya', 'Madhya'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil', 'Tamil'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar_Pradesh', 'Uttar_Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman_and_Nicobar_Islands', 'Andaman_and_Nicobar_Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra_and_Nagar_Haveli_Daman_and_Diu', 'Dadra_and_Nagar_Haveli_Daman_and_Diu'), ('Jammu_and_Kashmir', 'Jammu_and_Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], max_length=250)),
                ('zip_code', models.IntegerField()),
                ('alternate_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address_type', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=250)),
                ('batch_number', models.CharField(max_length=250)),
                ('manufactur_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('mfg_by', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('discount', models.CharField(max_length=25)),
                ('gst', models.CharField(max_length=25)),
                ('mrp', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('medicine_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('addresses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_side.addressmodel')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_side.medicinemodel')),
            ],
        ),
    ]
