# Generated by Django 5.0.4 on 2024-04-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=250)),
                ('batch_number', models.CharField(max_length=250)),
                ('manufactur_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('mfg_by', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('discount', models.CharField(max_length=25)),
                ('gst', models.CharField(max_length=25)),
                ('mrp', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('medicine_details', models.TextField()),
            ],
        ),
    ]
