# Generated by Django 5.0.4 on 2024-04-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_side', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='AddressModel',
        ),
        migrations.DeleteModel(
            name='MedicineModel',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
