# Generated by Django 5.0.4 on 2024-04-20 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_side', '0002_remove_orderitem_addresses_remove_orderitem_medicine_and_more'),
        ('patient', '0004_remove_patient_id_alter_patient_primary_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('profile_photo', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('license_no', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('opening_schedule', models.TextField()),
                ('primary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=250)),
                ('batch_number', models.CharField(max_length=250)),
                ('manufactur_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('mfg_by', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('discount', models.CharField(max_length=25)),
                ('gst', models.CharField(max_length=25)),
                ('mrp', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('medicine_details', models.TextField()),
                ('available_sizes', models.CharField(max_length=100)),
                ('delievery_charges', models.CharField(max_length=100)),
                ('medicine_photo', models.CharField(max_length=100)),
                ('packaging_fees', models.CharField(max_length=100)),
                ('medical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_details', to='medical_side.medicalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('delievery_method', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='medical_side.medicinemodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_order', to='patient.patient')),
            ],
        ),
    ]
