# Generated by Django 5.0.4 on 2024-04-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_education_alter_patient_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
