# Generated by Django 5.0.4 on 2024-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_id_alter_patient_primary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(null=True),
        ),
    ]
