# Generated by Django 5.0.4 on 2024-04-19 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('comment', models.TextField()),
                ('rater_experience', models.TextField()),
                ('ratee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
                ('rater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
