# Generated by Django 5.0.4 on 2024-04-18 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_doctor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('primary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
