# Generated by Django 5.0.4 on 2024-04-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='job_time',
            field=models.CharField(default='full time', max_length=100),
        ),
    ]
