# Generated by Django 5.0.4 on 2024-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctorexperience_calculated_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
