# Generated by Django 5.0.4 on 2024-04-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_doctor_experience_doctor_language'),
        ('medical_side', '0003_initial'),
        ('patient', '0005_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('signature', models.CharField(max_length=100)),
                ('insurance', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_of_doctor', to='patient.patient')),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='prescription_tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('tablet_duration', models.CharField(max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptionTablet', to='doctor.prescription')),
                ('tablet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_tablet', to='medical_side.medicinemodel')),
            ],
        ),
    ]
