# Generated by Django 5.0.4 on 2024-04-20 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_appointment_prescription_prescription_tablet'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appintment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_received', to='doctor.doctor'),
        ),
    ]
