# Generated by Django 5.0.4 on 2024-04-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_appointment_appintment_status_appointment_doctor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appintment_status',
            new_name='appointment_status',
        ),
    ]
